FROM ubuntu:18.04
ENV USER=root
ENV PASSWORD=thispassword
ENV DEBIAN_FRONTEND=noninteractive 
ENV DEBCONF_NONINTERACTIVE_SEEN=true

COPY BloodHound BloodHound
COPY turbovnc_2.2.4_amd64.deb turbovnc_2.2.4_amd64.deb
COPY virtualgl_2.6.3_amd64.deb virtualgl_2.6.3_amd64.deb
COPY BloodHound/config/*.json /root/.config/bloodhound/
COPY BloodHoundExampleDB.db/ /var/lib/neo4j/data/databases/

RUN apt-get update && \
	echo "tzdata tzdata/Areas select America" > ~/tx.txt && \
	echo "tzdata tzdata/Zones/America select New York" >> ~/tx.txt && \
	debconf-set-selections ~/tx.txt && \
	apt-get install -y abiword gnupg libasound2 apt-transport-https wget software-properties-common ratpoison novnc websockify libxv1 libglu1-mesa xauth x11-utils xorg tightvncserver

RUN dpkg -i virtualgl_*.deb && \
	dpkg -i turbovnc_*.deb	



RUN umask 0077 && \
	mkdir ~/.vnc/ && \
	echo $PASSWORD | vncpasswd -f > ~/.vnc/passwd && \
	chmod 0600 ~/.vnc/passwd && \
	echo "set border 1" > ~/.ratpoisonrc  && \
	echo "exec BloodHound/BloodHound --no-sandbox">> ~/.ratpoisonrc && \
	openssl req -x509 -nodes -newkey rsa:2048 -keyout ~/novnc.pem -out ~/novnc.pem -days 3650 -subj "/C=US/ST=NY/L=NY/O=NY/OU=NY/CN=NY emailAddress=email@example.com"
EXPOSE 80
CMD /opt/TurboVNC/bin/vncserver && websockify -D --web=/usr/share/novnc/ --cert=~/novnc.pem 80 localhost:5901 && tail -f /dev/null